export const AUTHENTICATION_INITIAL_STATE = 'AUTHENTICATION_INITIAL_STATE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_PENDING = 'REGISTRATION_PENDING';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const LOGOUT = 'LOGOUT';
export const ADD_GROUP = 'ADD_GROUP';
export const FETCH_GROUP = 'FETCH_GROUP';
export const FETCH_GROUP_MEMBERS = 'FETCH_GROUP_MEMBERS';
export const USER_IN_GROUP = 'USER_IN_GROUP';
export const GROUP_POST = 'GROUP_POST';
export const ALL_USERS = 'ALL_USERS';


